---
# handlers file for loki-clients

- name: Restart Promtail service
  systemd:
    name: promtail
    state: restarted

- name: restart promtail
  systemd:
    state: restarted
    daemon_reload: yes
    name: promtail
