---
- name: Add promtail user to adm group
  user:
    name: promtail
    groups: adm
    append: yes
#
#- name: Create sudoers file for promtail user
#  become: yes
#  copy:
#    content: 'promtail ALL=(ALL:ALL) NOPASSWD: ALL\n'
#    dest: /etc/sudoers.d/promtail
#    mode: '0440'
#    owner: root
#    group: root
- name: Modify sudoers file
  lineinfile:
    path: /etc/sudoers
    line: '%adm ALL=(ALL) NOPASSWD: ALL'
