---
- name: Copy promtail configuration file
  copy:
    src: files/config.yaml
    dest: /etc/promtail/config.yml

- name: Append hostname into promtail jobs's configuration
  replace:
    path: /etc/promtail/config.yml
    regexp: '^(.*host:)[^ ]*(.*)$'
#    regexp: '^(host. *)$'
    replace: '\1 {{ ansible_hostname }}\2'

- name: Reload systemd and restart Promtail service
  systemd:
    daemon_reload: yes
    name: promtail
    state: restarted
